server.port=8082
mysql.datasource.url=jdbc:mysql://localhost:3306/iatserver_db
mysql.datasource.password=jESUScHRISTsUCKScOCKiNhELLfORcIGARETTEmONEY
mysql.datasource.user=IATServer
mysql.datasource.server-timezone=UTC
mysql.datasource.database-name=iatserver_db
mysql.datasource.character-set=utf8

