environment.downloadControllerPath=/DownloadSoftware
environment.clientSoftwareFilePath=/var/www/iat/ClientSoftware/IATDesign.zip
environment.clientSoftwareV10FilePath=/var/www/iat/ClientSoftware/IATDesignV10.zip
server.port=8082