server.port=8082
mysql.datasource.url=jdbc:mysql://localhost:3306/iatserver_db
mysql.datasource.password=vze4bcmipjiQfOwm
mysql.datasource.user=IATServer
mysql.datasource.server-timezone=UTC
mysql.datasource.database-name=iatserver_db
mysql.datasource.character-set=utf8
environment.downloadControllerPath=/DownloadSoftware
environment.clientSoftwareFilePath=/var/www/iat/IATDesign.zip
mail.smtp.auth=true
mail.smtp.starttls.enable=false
mail.smtp.quitwait=false
mail.host=127.0.0.1
mail.port=25
mail.protocol=smtp
mail.username=iatsoftware
mail.password=NDRD25Bb_HTNF42c
mail.username.error-reprt-recipient=sysinfo
mail.password.errorreport=NDRD25b_HTNF42c
mail.user-personal.errorreport=Error Reporter
mail.user-personal=IAT Software
mail.user-address=iatsoftware@iatsoftware.net
mail.image.logo-url=https://iatsoftware/images/logo.png
mail.image.logo-classpath-location=classpath:email/images/logo.png
mail.image.header-url=https://iatsoftware.net/images/header.png
mail.image.header-classpath-location=classpath:email/images/header.png