mail.host=127.0.0.1
mail.port=25
mail.protocol=smtp
mail.username=iatsoftware
mail.password=ytND42_)f
mail.username.errorreport=sysinfo
mail.password.errorreport=./Fuck1PollockCunt
mail.user-personal.errorreport=Error Reporter
mail.user-personal=IAT Software
mail.user-address=iatsoftware@iatsoftware.net
mail.image.logo-url=https://iatsoftware/images/logo.png
mail.image.logo-classpath-location=classpath:email/images/logo.png
mail.image.header-url=https://iatsoftware.net/images/header.png
mail.image.header-classpath-location=classpath:email/images/header.png